# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM registry.redhat.io/openshift/golang-builder:golang-builder-v1.26-rhel9 AS builder

WORKDIR /workspace/locutus

COPY locutus/ .

RUN GO111MODULE="on" CGO_ENABLED=1 GOFLAGS="" go build

FROM registry.redhat.io/ubi9/ubi-minimal-pqc:latest

WORKDIR /

COPY --from=builder /workspace/locutus/locutus /locutus

COPY jsonnet/main.jsonnet /
COPY jsonnet/obs-operator.jsonnet /
COPY jsonnet/config.yaml /

COPY jsonnet/vendor/github.com/stolostron/observatorium-deployment/configuration/components/ /vendor/stolo-configuration/components/
COPY jsonnet/vendor/github.com/stolostron/kube-thanos/jsonnet/kube-thanos/ /vendor/kube-thanos/
COPY jsonnet/vendor/github.com/stolostron/thanos-receive-controller/jsonnet/lib/ /vendor/thanos-receive-controller/
COPY jsonnet/vendor/github.com/stolostron/observatorium/jsonnet/lib/ /vendor/lib/
COPY jsonnet/vendor/github.com/observatorium/api/jsonnet/lib/ /vendor/observatorium-api/
COPY jsonnet/vendor/github.com/observatorium/observatorium/configuration/components/loki.libsonnet /vendor/github.com/observatorium/observatorium/configuration/components/

RUN chgrp -R 0 /vendor && chmod -R g=u /vendor

ARG BUILD_DATE
ARG VCS_REF
ARG DOCKERFILE_PATH
ARG VCS_BRANCH
ARG IMAGE_VERSION
ARG IMAGE_RELEASE

LABEL name="rhacm2/observatorium-rhel9-operator" \
    cpe="cpe:/a:redhat:acm:5.1::el9" \
    summary="observatorium-operator" \
    vendor="Red Hat, Inc." \
    release="$IMAGE_RELEASE" \
    com.redhat.component="observatorium-operator" \
    description="Observatorium Operator" \
    io.openshift.tags="observability" \
    io.k8s.display-name="observatorium/operator" \
    io.k8s.description="Observatorium Operator" \
    maintainer="Observatorium <team-monitoring@redhat.com>" \
    version="$IMAGE_VERSION" \
    org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.description="Observatorium Operator" \
    org.label-schema.docker.cmd="docker run --rm observatorium/operator" \
    org.label-schema.docker.dockerfile=$DOCKERFILE_PATH \
    org.label-schema.name="observatorium/operator" \
    org.label-schema.schema-version="1.0" \
    org.label-schema.vcs-branch=$VCS_BRANCH \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/observatorium/operator" \
    org.label-schema.vendor="Red Hat, Inc." \
    org.label-schema.version=$IMAGE_VERSION

COPY LICENSE /licenses/

USER 1001:1001

ENTRYPOINT ["/locutus", "--renderer=jsonnet", "--renderer.jsonnet.entrypoint=main.jsonnet", "--trigger=resource", "--trigger.resource.config=config.yaml"]
