apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/observatorium-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-2.14"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: release-acm-214
    appstudio.openshift.io/component: observatorium-operator-acm-214
    pipelines.appstudio.openshift.io/type: build
  name: observatorium-operator-acm-214-on-push
  namespace: crt-redhat-acm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/observatorium-operator-acm-214:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/ppc64le
    - linux/s390x
    - linux/arm64
  - name: dockerfile
    value: Containerfile.operator
  - name: path-context
    value: .
  - name: hermetic
    value: true
  - name: prefetch-input
    value: '[{"path": ".", "type": "gomod"}, {"path": "locutus/", "type": "gomod"}]'
  - name: build-source-image
    value: "true"
  - name: build-args
    value:
    - IMAGE_VERSION=2.14.0
    - IMAGE_RELEASE={{revision}}
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-observatorium-operator-acm-214
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
