name: lint & check generated

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check generated files are up to date
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Vendor dependencies
        run: go mod vendor

      - name: Regenerate deepcopy
        run: make generate

      - name: Regenerate CRD manifests
        run: make manifests/crds/core.observatorium.io_observatoria.yaml

      - name: Check for uncommitted changes
        run: git diff --exit-code
